services:
  node:
    container_name: astor_node
    user: node
    build: ./.docker/node
    volumes:
      - ./:/home/node/astor
    working_dir: /home/node/astor
    ports:
      - "8099:8080"
      - "4000:4000"
    tty: true